name: Compare json key

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    permissions:
      contents: none
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Compare
        run: |
          if [[ $(diff <(cat A.json | jq -r '[paths | join(".")]') <(cat B.json | jq -r '[paths | join(".")]')) ]]
          then
            echo "$(diff -c <(cat A.json | jq -r '[paths | join(".")]') <(cat B.json | jq -r '[paths | join(".")]'))"
            exit 1;
          else
            echo "No diff"
          fi
