name: Compare json key

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    permissions:
      contents: none
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Compare
        run: |
          IS_DIFF=$(diff <(jq -r '[paths | join(".")]' A.json) <(jq -r '[paths | join(".")]' B.json))
