name: Build and deploy Angular app to an Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

env:
  WEBAPP_NAME:  $GITHUB_REF##*/

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v3
    - name: echo env
      run: |
        echo "var WEBAPP_NAME: $WEBAPP_NAME"
    
  #   - name: Zip artifact for deployment
  #     run: |
  #       zip release.zip ./* -r

  #   - name: Upload artifact for deployment job
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: my-app
  #       path: ./release.zip

  # ReuseableMatrixJobForDeployment:
  #   needs: build
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       target: [Development, Production ]
  #   uses: ./.github/workflows/deployment.yml
  #   with:
  #     target-env: ${{ matrix.target }}
  #   secrets: inherit
