name: Build and deploy Angular app to an Azure Web App

on:
  workflow_dispatch:
    branches:
      - 'trigger-manual'

env:
  WEBAPP_NAME:  ${{ vars.WEBAPP_NAME_IN_ENV }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

    # - uses: actions/checkout@v3
    - name: echo env
      run: |
        echo "var WEBAPP_NAME: $WEBAPP_NAME"
        APP_VERSION=$(date +'%Y-%m-%dT%H:%M:%S')
        echo "APP_VERSION=$APP_VERSION"
        echo "VERSION_LABEL=archway-to-careers-api-dev-$APP_VERSION"
    
  #   - name: Zip artifact for deployment
  #     run: |
  #       zip release.zip ./* -r

  #   - name: Upload artifact for deployment job
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: my-app
  #       path: ./release.zip

  # ReuseableMatrixJobForDeployment:
  #   needs: build
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       target: [Development, Production ]
  #   uses: ./.github/workflows/deployment.yml
  #   with:
  #     target-env: ${{ matrix.target }}
  #   secrets: inherit
