name: Workflow dispatch

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Envirnment"
        type: choice
        options:
          - dev
          - prod
      project:
        type: string
        required: true
        description: "Input project name"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3

      - name: echo input
        run: |
          echo "Input environment: ${{ inputs.environment }}"
          echo "Input project: ${{ inputs.project }}"

      - name: ifelse
        run: |
          if [[ ${{ inputs.environment }} == "dev" ]]; then
            echo "dev"
          else
            echo "prod"
          fi
